### ISSUE TITLE
Mods Skipped in SMAPI

### ISSUE THREAD

**Issue by Plastic666** [janfokke/StardewValleyDutch#1]
Hi Janfokke,

Somehow I get a message with skipped mods.
Installed SMAPI and pasted the files of your GIthub in the Mods folder.

![afbeelding](https://user-images.githubusercontent.com/81385374/112528506-83c7e280-8da4-11eb-9713-d695aab755b6.png)

thanks allready for all your efforts!

**Comment by janfokke** [comment]
Hi Plastic666,

I think you extracted the contents of StardewValleyDutch into your mods folder. You have to put the 
StardewValleyDutch folder into your mods folder.

Like this
![afbeelding](https://user-images.githubusercontent.com/17224428/112638379-7c094c00-8e3f-11eb-9a6e-7f0e269a77d2.png)

Also, make sure you have [ContentPatcher ](https://www.nexusmods.com/stardewvalley/mods/1915) installed.
I saw that I didn't have that in the description yet, so I've added that now

**Comment by Plastic666** [comment]
Hi Janfokke. This did actually solve the issue. 
The stardewvalleydutch folder is actually not part of the .zip file. I created it and now it works like a gem. Thanks again for all the efforts. 👍
