### ISSUE TITLE
Officiëel doorvoeren?

### ISSUE THREAD

**Issue by DeltaBlast** [janfokke/StardewValleyDutch#16]
Fantastisch werk allemaal! Nou kan ik dit met m'n kids spelen!

Maarre... is er al contact geweest met CA om dit gewoon officieel door te voeren? Ik zou verwachten dat hij daar alleen maar blij mee kan zijn en dan kan iedereen het enjoyen 🤔

**Comment by azelion** [comment]
Hey,

Ik kom nog enkele grove fouten tegen. Ik heb een programmaatje gemaakt wat
teksten toegevoegd en er zit her-en-der een misalignment in de files
waardoor e.e.a. nog niet klopt, dus geef me nog even iets langer om dingen
te fixen.

Ik heb zeker geen contact met de officiële maker hierover, misschien wel
vet eigenlijk. Maar zoals hierboven benoemd, ben ik nog niet met alles
tevreden.

Mvg,
Joris

**Comment by DeltaBlast** [comment]
Prima, ik wilde eigenlijk sowieso wachten met m'n volgende run tot 1.6 uitkwam op android, de kids hebben allemaal een tablet en zijn niet zo goed met de pc. Hopelijk is dat tegen die tijd ook allemaal compatible 😁

**Comment by azelion** [comment]
Ik voer nog steeds redelijk vaak verbeteringen door. Vooral in leesbaarheid, onjuiste vertalingen (ik ben al veel over vissoorten te weten gekomen), dus officiëel proberen te maken lijkt me geen haalbare doelstelling op korte termijn tenzij er meer controle op de code gedaan kan worden. 

Daarom mijn voorstel om dit issue te sluiten.

**Comment by DeltaBlast** [comment]
Dat je een perfectionist bent maakt het nog niet "niet haalbaar" 😅
Voor een officiele vertaling moet misschien wel compleet andere code gebruikt worden anyway, maar je hebt iig de referentie al. Dus als ik jou was zou ik gewoon een mailtje sturen naar contact@stardewvalley.net met "hey ik heb een nederlandse vertaling gemaakt, wil je die misschien officieel in de game stoppen?" en dan kijken wat er uit komt... misschien wil hij je er wel voor betalen om de laatste puntjes op de i te zetten :)

Maar ik zal hem dichtgooien 😎
Hoe dan ook: thanks voor all the hard work!
