### ISSUE TITLE
geen vertaling voor characters

### ISSUE THREAD

**Issue by siyven** [janfokke/StardewValleyDutch#23]
Hallo, 
Geen idee of dit hoort of niet maar alles is vertaald behalve de characters zelf. Komt dit nog of is dit een issue in mijn game zelf?

**Comment by azelion** [comment]
Hey, wat bedoel je precies? De namen van de npc's?

**Comment by siyven** [comment]
Hoi, sorry ik bedoelde dialoog van de characters. Dat staat nog allemaal in het engels bij mij.

**Comment by azelion** [comment]
Heb je de Duitse taal gekozen zoals in de instructies?

**Comment by siyven** [comment]
Ja dat heb ik gedaan.

**Comment by azelion** [comment]
En je start met SMAPI? Krijg je eenzelfde soort scherm?
![image](https://github.com/janfokke/StardewValleyDutch/assets/7515386/bbacac34-c699-492b-b196-74e0df419e62)

**Comment by azelion** [comment]
Hmmmm, heel raar, zeker ook omdat ze dan Engels praten... 

Misschien kun je de logs van Smapi eens delen, misschien zie ik daar iets in staan wat moet klopt.

Optie twee:
Ik heb een andere aanpak qua vertalen gemaakt, waarmee vertalen in andere mods naar het Nederlands een mogelijkheid wordt. Probeer de code van dev/1.6.15 eens, mogelijk werkt dit? Hiervoor moet je bij taal kiezen naar de volgende pagina

**Comment by azelion** [comment]
Is dit probleem nog opgelost met de nieuwste versie?

**Comment by azelion** [comment]
Geen reactie, niet reproduceerbaar

**Comment by siyven** [comment]
Excuses ik heb uw bericht niet meer gezien. Jammer hopelijk lukt het me in de toekomst wel

**Comment by azelion** [comment]
Ah okay, de laatste versie is anders georganiseerd. Probeer eens of die wel werkt. Daardoor op het taalkeuze scherm naar rechts klikken en Nederlands selecteren.

**Comment by siyven** [comment]
Helaas spreken de npc's nog steeds engels, Ik heb de mod weg gehaald en opnieuw gedownload en ik heb de taalkeuze veranderd

**Comment by siyven** [comment]
Hallo het probleem is opgelost het werkt nu voor mij. Ik denk dat er een mod is geweest waar hij niet mee samen kan werken. Heel erg bedankt!!

**Comment by azelion** [comment]
Oh dat klinkt volledig logisch eigenlijk!
Stardew Valley expanded toevallig? Misschien dat ik daar ooit nog eens aan begin, maar voel je vrij die te doen. 😄

**Comment by siyven** [comment]
ja die had ik inderdaad in de mod lijst staan haha. oh nee ik ben geen vertaler ik speel alleen engels, deze mod is perfect voor een bewoonster bij mijn werk, ze wil graag stardew spelen maar kan niet engels dus vandaar haha.  suc6 met het vertalen en heel erg bedankt voor het maken van de mod! ze is heel gelukkig.
