### ISSUE TITLE
De mod werkt niet meer sinds versie 1.6.9  van Stardew valley 

### ISSUE THREAD

**Issue by Gaming-pandatje** [janfokke/StardewValleyDutch#28]
In de huidige versie van Stardew valley 1.6.14 werkt de mod spijtig genoeg niet meer. Dit komt waarschijnlijk door wijzigingen in de game in 1.6.9. Zou de update kunnen geupdate worden?

https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6.9

**Comment by Gaming-pandatje** [comment]
En ik ben niet de enige met dit probleem dus het ligt zeker aan de update.![Screenshot_20241208-143219.png](https://github.com/user-attachments/assets/a944c790-a3ce-4355-bf2e-4367fd2cab51)

**Comment by azelion** [comment]
Oef, heb even door de changes heen gekeken... Ziet eruit als wel wat werk. Ik ga kijken of ik voor de kerst nog tijd heb, anders op mn gemak in de vakantie

**Comment by Gaming-pandatje** [comment]
> In de huidige versie van Stardew valley 1.6.14 werkt de mod spijtig genoeg niet meer. Dit komt waarschijnlijk door wijzigingen in de game in 1.6.9. Zou de mod kunnen geupdate worden?
> 
> https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6.9

**Comment by Gaming-pandatje** [comment]
Is er een progress update?

**Comment by azelion** [comment]
Hey, mogelijk was 't toch een erg kleine, zou je eens kunnen kijken of het werkt voor je @Gaming-pandatje ?
Works on my machine. :)

**Comment by Gaming-pandatje** [comment]
Ja bij mij werkt het ook
