### ISSUE TITLE
Android/mobile ondersteuning

### ISSUE THREAD

**Issue by EwoutVDC** [janfokke/StardewValleyDutch#4]
Super vertaling! Maar Content Patcher 1.21 bestaat nog niet voor Android.
Door in content.json "Format" op 1.19 te zetten, wordt de mod wel geladen en werken alle vertalingen die er in zitten voor zo ver ik kan zien.
Ik weet niet of er beperkingen zijn die ik nog niet gemerkt heb door format 1.19 te gebruiken? Anders kan dat misschien standaard gebruikt worden zodat de mod ook werkt voor android zonder edits.

Er zijn wel nog missende strings voor de mobile UI, maar dat is geen groot probleem en kan eventueel later toegevoegd worden als jullie dat zien zitten.

**Comment by EwoutVDC** [comment]
Op de tablet (samsung tab A 10.1 2019) wou de mod niet laden. Ik kreeg een "object reference not set to instance of object" foutmelding. Ik denk bij het laden van de title buttons?. Als ik die weg haal uit de content.json, dan laadt de mod wel.
Nog eens bedankt voor de vertaling, dit is fantastisch voor mijn zoon van 8!

**Comment by janfokke** [comment]
Ik heb de mod nog niet getest op android, maar goed om te horen dat je hem aan de praat hebt gekregen. 
Wellicht maak ik daar een eigen versie voor.

**Comment by rhansenne** [comment]
De laatste master versie is nu ook compatibel met Android en bevat de vertalingen voor de ontbrekende strings.

**Comment by azelion** [comment]
https://github.com/janfokke/StardewValleyDutch/releases/tag/1.5.0 bevat de vertalingen voor mobile/1.5 daarmee lijkt dit me opgelost.
