### ISSUE TITLE
Werkt niet

### ISSUE THREAD

**Issue by JustName1** [janfokke/StardewValleyDutch#5]
Hallo.

Helaas werkt hij niet. Ik heb alle stappen ondernomen maar krijg dit in SMAP te zien:
Verder heb ik de content patcher laten installeren en plaatsen in de Stardew map.

[SMAPI] SMAPI 3.15.0 with Stardew Valley 1.5.6 (build 22018) on Microsoft Windows 11 Home
[SMAPI] Mods go here: D:\Gaming\Steam\steamapps\common\Stardew Valley\Mods
[SMAPI] Waiting for game to launch...
[SMAPI] Loading mod metadata...
[SMAPI] Loading mods...
[SMAPI] Loaded 3 mods:
[SMAPI]    Console Commands 3.15.0 by SMAPI | Adds SMAPI console commands that let you manipulate the game.
[SMAPI]    Error Handler 3.15.0 by SMAPI | Handles some common vanilla errors to log more useful info or avoid breaking the game.
[SMAPI]    Save Backup 3.15.0 by SMAPI | Automatically backs up all your saves once per day into its folder.

[SMAPI] Found 1 mod with warnings:
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.

[SMAPI]       - StardewValley Dutch 1.0.0 because it requires mods which aren't installed (Content Patcher: https://www.nexusmods.com/stardewvalley/mods/1915).

**Comment by janfokke** [comment]
Heb je Content Patcher geïnstalleerd?
https://www.nexusmods.com/stardewvalley/mods/1915

**Comment by JustName1** [comment]
Ja.. SMAPI, vervolgens de CP in mods samen met de vertaling mod.

**Comment by janfokke** [comment]
Ik heb hem net geïnstalleerd en bij mij werkt het gewoon.
Als je discord hebt, kan ik eventueel even meekijken JanFokke#9799

**Comment by JustName1** [comment]
Late reactie. Opnieuw geprobeerd. Nu de melding:

[SMAPI]    No update keys
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods have no update keys in their manifest. SMAPI may not notify you about updates for these
[SMAPI]       mods. Consider notifying the mod authors about this problem.

[SMAPI]       - StardewValley Dutch
