### ISSUE TITLE
Vertaling voor Expanded, Ridgeside Village en East Scarp mod?

### ISSUE THREAD

**Issue by BohorquezJ** [janfokke/StardewValleyDutch#6]
Beste,

Ontzettend bedankt voor het vertalen van Stardew Valley: mijn kinderen hebben er erg veel plezier van! 
Zijn jullie van plan om de populaire mods Stardew Valley Expanded, Ridgeside Village en East Scarp te vertalen? Indien nodig kan ik helpen met vertalen van het Engels naar het Nederlands. Deze mods verlengen de spelduur aanzienlijk. Hier zullen erg veel mensen plezier van hebben.

**Comment by azelion** [comment]
Ik heb de methode van vertalen aangepast. Om dit door te voeren zal er een vertaling in de i18n van de desbetreffende mods gemaakt moeten worden.

Voor een voorbeeld zie mijn pr hier: https://github.com/Sakorona/SDVMods/pull/103

Ticket kan niet hier opgelost worden.
