### ISSUE TITLE
Community Center Golden Scroll crash

### ISSUE THREAD

**Issue by ShriveledSquirrel** [janfokke/StardewValleyDutch#9]
The camera locks up and the game crashes upon interacting with the Golden Scroll in the Community Center after the initial cutscene. Fix for modders found here: http://forums.stardewvalley.net/threads/bug-community-bundles-still-crashing.3120/post-65144

In the meantime, players can manually fix it themselves by following these instructions: http://forums.stardewvalley.net/threads/bug-community-bundles-still-crashing.3120/post-20942 (Although the poster says not to proceed if the number is greater than 31, it worked for me when I changed mine from 35 to 30.)

**Comment by ShriveledSquirrel** [comment]
You can also avoid this issue entirely if you first create your world in English, then swap to German (Dutch mod). You do not need to create the world before adding the mod. This would mean that you wouldn't be able to read the intro in Dutch, however.

**Comment by azelion** [comment]
Issue niet reproduceerbaar in 1.6
